package org.itmo;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CommentTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void comment() {
        // Test name: comment
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://dfiles.ru/");
        // 2 | setWindowSize | 1147x1435 |
        driver.manage().window().setSize(new Dimension(1147, 1435));
        // 3 | click | linkText=Емкость батареи Galaxy S25 Ultra может вас разочаровать |
        driver.findElement(By.linkText("Емкость батареи Galaxy S25 Ultra может вас разочаровать")).click();
        // 4 | runScript | window.scrollTo(0,107) |
        js.executeScript("window.scrollTo(0,107)");
        // 5 | runScript | window.scrollTo(0,1340) |
        js.executeScript("window.scrollTo(0,1340)");
        // 6 | runScript | window.scrollTo(0,1433) |
        js.executeScript("window.scrollTo(0,1433)");
        // 7 | runScript | window.scrollTo(0,2292) |
        js.executeScript("window.scrollTo(0,2292)");
        // 8 | click | id=author |
        driver.findElement(By.id("author")).click();
        // 9 | type | id=author | hello
        driver.findElement(By.id("author")).sendKeys("hello");
        // 10 | click | id=email |
        driver.findElement(By.id("email")).click();
        // 11 | type | id=email | 2398768715@qq.com
        driver.findElement(By.id("email")).sendKeys("2398768715@qq.com");
        // 12 | click | id=comment |
        driver.findElement(By.id("comment")).click();
        // 13 | type | id=comment | test
        driver.findElement(By.id("comment")).sendKeys("test");
    }
}