package org.itmo;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.*;

public class MainTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

        setWindowSize(1920, 1080);
        setWebSite("https://dfiles.ru/");
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    public void setWindowSize(int width, int height) {
        driver.manage().window().setSize(new Dimension(width, height));
    }

    public void setWebSite(String url) {
        driver.get(url);
    }

    /**
     * Test for opening news page
     */
    @Test
    public void getNews() {
        driver.findElement(By.xpath("//li[1]")).click();
    }

    /**
     * Test for opening articles page
     */
    @Test
    public void getArticles() {
        driver.findElement(By.xpath("//li[2]")).click();
    }

    /**
     * Test for opening smartphones rating page
     */
    @Test
    public void getRatingOfPhones() {
        {
            WebElement element = driver.findElement(By.xpath("//li[3]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.xpath("//a[contains(text(),\'Рейтинги смартфонов\')]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.xpath("//a[contains(text(),\'Сравнение смартфонов\')]")).click();
    }

    @Test
    public void getRatingOfProcessors() {
        {
            WebElement element = driver.findElement(By.xpath("//li[3]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.xpath("//a[contains(text(),\'Рейтинги смартфонов\')]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.xpath("//a[contains(text(),\'Мобильные процессоры\')]")).click();
    }
}