package org.itmo;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

public class MainTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

        setWindowSize(1920, 1080);
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    public void setWindowSize(int width, int height) {
        driver.manage().window().setSize(new Dimension(width, height));
    }



    /**
     * Test for opening news page
     */
    @Test
    public void getNews() {
        driver.get("https://dfiles.ru/");
        driver.findElement(By.xpath("/html/body/div[2]/header/div[1]/div[3]/ul/li[1]")).click();
    }

    /**
     * Test for opening articles page
     */
    @Test
    public void getArticles() {
        driver.get("https://dfiles.ru/");
        driver.findElement(By.xpath("/html/body/div[2]/header/div[1]/div[3]/ul/li[2]")).click();
    }

    @Test
    public void getRatingOfPhones() {
        driver.get("https://dfiles.ru/");

        {
            WebElement element = driver.findElement(By.xpath("/html/body/div[2]/header/div[1]/div[3]/ul/li[3]/a"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }

        {
            WebElement element = driver.findElement(By.cssSelector("#top-menu > #menu-item-219010 > a"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector("#top-menu > #menu-item-219010 #menu-item-215653 > a")).click();
    }
}